"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isKeyNumberValue = exports.isNumberArray = exports.isNonEmpty = exports.isArray = exports.isCallable = exports.isKeyValue = exports.isString = exports.isNumber = void 0;
const isNumber = (v) => typeof v === "number";
exports.isNumber = isNumber;
const isString = (v) => typeof v === "string";
exports.isString = isString;
const isKeyValue = (v) => typeof v === "object" && !(0, exports.isArray)(v) && v !== null;
exports.isKeyValue = isKeyValue;
const isCallable = (v) => typeof v === "function" && !v.toString().startsWith("class");
exports.isCallable = isCallable;
const isArray = (v) => Array.isArray(v);
exports.isArray = isArray;
const isNonEmpty = (a) => a.length > 0;
exports.isNonEmpty = isNonEmpty;
const isNumberArray = (v) => Array.isArray(v) && v.every(v => (0, exports.isNumber)(v));
exports.isNumberArray = isNumberArray;
const isKeyNumberValue = (v) => (0, exports.isKeyValue)(v) && Object.values(v).every(v => (0, exports.isNumber)(v));
exports.isKeyNumberValue = isKeyNumberValue;
