import type { Properties } from 'csstype';
import { AllCombinations, CamelOrPascalToKebab, IfTrueFalseExtends, IfUndefinedOtherExtends, PropertiesUnion, Writable } from 'src/types';
import { KeyValue } from 'src/types_checks';
export type CSSPropertyKey = keyof Properties;
export type CSSProperties<K extends CSSPropertyKey = CSSPropertyKey> = Pick<Properties, K>;
export type CSSPropertyValue<K extends CSSPropertyKey = CSSPropertyKey> = CSSProperties[K];
export declare const d: CSSPropertyValue<"width">;
export type CSSPropertyStr<K extends CSSPropertyKey> = K extends K ? `${CamelOrPascalToKebab<K>}:${CSSProperties[K]};` : never;
export type CSSFunctionStr<K extends CSSPropertyKey> = K extends K ? `${CamelOrPascalToKebab<K>}(${string})` : never;
type MapProperty<K extends CSSPropertyKey, PM extends KeyValue> = (properties: PM) => CSSProperties[Exclude<K, undefined>];
type MapProperties<K extends CSSPropertyKey, PM extends KeyValue> = (properties: PM) => CSSProperties[Exclude<K, undefined>];
type MapPropertiesOrUndefined<K extends CSSPropertyKey | undefined, MP extends KeyValue> = IfUndefinedOtherExtends<K, MapProperties<Exclude<K, undefined>, MP>>;
type ToFunction<K extends CSSPropertyKey | undefined> = IfUndefinedOtherExtends<K, boolean, false>;
export type CSSObjectOneKey<K extends CSSPropertyKey | undefined, PM extends KeyValue, TF extends ToFunction<K>> = Readonly<{
    key: K;
    mapProperties: MapPropertiesOrUndefined<K, PM>;
    keyValue: IfUndefinedOtherExtends<K, PropertiesUnion<CSSProperties<Exclude<K, undefined>>>>;
    string: IfUndefinedOtherExtends<K, CSSPropertyStr<Exclude<K, undefined>>>;
    toFunction: TF;
    functionString: IfTrueFalseExtends<TF, CSSFunctionStr<Exclude<K, undefined>>, undefined>;
}> & PM;
export declare const cssObjectOneKey: CSSObjectOneKey<CSSPropertyKey | undefined, KeyValue, boolean>;
export declare const newCssObjectOneKey: <K extends keyof Properties<0 | (string & {}), string & {}> | undefined, PM extends KeyValue, TF extends ToFunction<K>>(key: K, mapProperties: MapPropertiesOrUndefined<K, PM>, properties: PM) => CSSObjectOneKey<K, PM, TF>;
type PropertiesToMap = KeyValue<CSSPropertyKey>;
export type CSSObjectMultipleKeys<PM extends Writable<PropertiesToMap> | undefined, TF extends IfUndefinedOtherExtends<PM, boolean, false>> = Readonly<{
    mapProperty: IfUndefinedOtherExtends<PM, MapProperty<Exclude<PM, undefined>>>;
    keyValue: IfUndefinedOtherExtends<PM, CSSProperties<Extract<keyof PM, CSSPropertyKey>>>;
    string: IfUndefinedOtherExtends<PM, AllCombinations<CSSPropertyStr<Extract<keyof PM, CSSPropertyKey>>>>;
    toFunction: TF;
    functionString: IfTrueFalseExtends<TF, AllCombinations<CSSFunctionStr<Extract<keyof PM, CSSPropertyKey>>>, undefined>;
}> & (PropertiesToMap extends PM ? Pick<Exclude<PM, undefined>, CSSPropertyKey> : never);
export declare const cssObjectMultipleKeys: CSSObjectMultipleKeys<PropertiesToMap | undefined, boolean>;
export {};
